# Generated by Django 5.2.3 on 2025-06-24 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extensao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('img', models.TextField()),
                ('manual', models.TextField(blank=True, null=True)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('img', models.TextField()),
                ('max_players', models.IntegerField()),
                ('duracao', models.TimeField()),
                ('ano', models.IntegerField()),
                ('manual', models.TextField(blank=True, null=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.jogo')),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.AddField(
            model_name='extensao',
            name='jogo_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.jogo'),
        ),
    ]
