# Generated by Django 5.2.3 on 2025-06-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_extensao_genero_jogo_noticia_delete_produto_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='extensao',
            table='extensao',
        ),
        migrations.AlterModelTable(
            name='genero',
            table='genero',
        ),
        migrations.AlterModelTable(
            name='jogo',
            table='jogo',
        ),
        migrations.AlterModelTable(
            name='noticia',
            table='noticia',
        ),
    ]
